FROM alpine:latest

RUN apk update && apk add jq && apk add curl && apk add bash
COPY scripts/restaurant_journey.sh /opt/restaurant_journey.sh
RUN chmod 0755 /opt/restaurant_journey.sh
ENTRYPOINT ["/opt/restaurant_journey.sh"]
